name: Semgrep
on: 
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: 55 14 * * *
jobs:
  semgrep:
    strategy:
      matrix:
        subdir:
          - cloud-devops-ci-cd-udapeople
          - cloud-devops-cloudformation
          - cloud-devops-operationalizing-ml
          - cloud-devops-static-website  
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_REPO_DISPLAY_NAME: monorepo-test--${{ matrix.subdir }}
      SEMGREP_BASELINE_REF: cloudsenseiNG-patch-1
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: SEMGREP_BASELINE_REF="$SEMGREP_BASELINE_REF" semgrep ci --include=${{ matrix.subdir }}

