name: Semgrep
on: 
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
    - cron: 55 14 * * *  
    
jobs:
  semgrep:
    strategy:
      matrix:
        subdir:
          - cloud-devops-cloudformation
          - cloud-devops-static-website  
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_REPO_DISPLAY_NAME: monorepo-test--${{ matrix.subdir }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci --json --output report-${{ matrix.subdir }}.json --include=${{ matrix.subdir }} || true
    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-report
        path: report-${{ matrix.subdir }}.json
        retention-days: 1

  merge-reports:
    # Merge reports after semgrep_include, even if some jobs have failed
    if: always()
    needs: [semgrep]
    runs-on: ubuntu-20.04

    steps:
    - name: Download all reports
      uses: actions/download-artifact@v3
      with:
        name: semgrep-report
        path: semgrep-report

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Combine reports
      run: jq -s 'reduce .[] as $item ({}; . + $item)' semgrep-report/*.json > combined_report.json

    - name: Upload combined report
      uses: actions/upload-artifact@v3
      with:
        name: combined-semgrep-report
        path: combined_report.json
        retention-days: 14
