name: Semgrep
on:
<<<<<<< HEAD
  pull_request: {}
=======
  pull_request_target: {}
>>>>>>> c2aca8f3f0215adbc07defd9ec435374f772d18b
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 55 14 * * *

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} 
    steps:
    - uses: actions/checkout@v4
<<<<<<< HEAD
    - run: semgrep ci
=======
    - run: semgrep ci --include=${{ matrix.subdir }} 
>>>>>>> c2aca8f3f0215adbc07defd9ec435374f772d18b
